server:
  port: '8092'
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:user?allowMultiQueries=true;
    driverClassName: org.h2.Driver
    password: ''