server:
  port: '9999'
  servlet:
    context-path: /sample

spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:member?allowMultiQueries=true;
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  api:
    version: v1

#  logging.level:
#    org.hibernate.SQL: debug